config/routes.rb
Rails.application.routes.draw do
  post '/login', to: 'authentication#login'

  # users
  resources :users, only: %i[new create show index] do
    member do
      post :toggle_follow
    end
  end

  # posts
  resources :posts, only: %i[new create index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

# Post model
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :thumbnail
  validates_presence_of :title, :content, :description

  validates :description, length: { maximum: 200 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
# frozen_string_literal: true

# Class responsible for all the functionality for the user model.
class User < ApplicationRecord
  before_create { |user| user.set_role('reader') }

  has_one_attached :profile_image
  belongs_to :role, optional: true

  has_many :posts
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy

  has_many :passive_relationships,  class_name: 'Relationship',
                                    foreign_key: 'followed_id',
                                    dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  validates_presence_of :name
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  def set_role(role_name)
    self.role = Role.find_by(name: role_name)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                      WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end

  def discover
    following_ids = "SELECT followed_id FROM relationships
                      WHERE follower_id = :user_id"
    Post.where("user_id NOT IN (#{following_ids}) AND user_id != :user_id", user_id: id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def posts
    Post.where(user_id: id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Main controller all controllers are based on.
class ApplicationController < ActionController::API
  attr_reader :current_user

  def not_found(type = '')
    render json: { error: "#{type} not found" }, status: 404
  end

  def authorize_request
    header = request.headers['Authorization']
    header = header.split(' ').last if header
    begin
      @decoded = JsonWebToken.decode(header)
      @current_user = User.find(@decoded[:user_id])
    rescue ActiveRecord::RecordNotFound
      render json: { errors: 'Unauthorized user' }, status: :unauthorized
    rescue JWT::DecodeError
      render json: { errors: 'Invalid token' }, status: :unauthorized
    end
  end

  def can_post?
    if @current_user&.role&.name == 'writer'
      true
    else
      render json: { errors: 'Forbidden action: creating post' }, status: :forbidden
    end
  end
end

app/controllers/authentication_controller.rb
# frozen_string_literal: true

# Class for controlling user auth.
class AuthenticationController < ApplicationController
  # POST /auth/login
  def login
    @user = User.find_by_email(params[:email])
    @user.role_id = Role.find(@user.role_id).external_role_id
    if @user&.authenticate(params[:password])
      token = JsonWebToken.encode(user_id: @user.id)
      time = Time.now + 24.hours.to_i
      render json: {
        token: token,
        exp: time.strftime('%m-%d-%Y %H:%M'),
        user: @user
      }, status: :ok
    else
      render json: { error: 'unauthorized' }, status: :unauthorized
    end
  end

  def login_params
    params.permit(:email, :password)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Controller responsible for handling requests related to posts.
class PostsController < ApplicationController
  before_action :authorize_request, only: [:create]
  before_action :can_post?, only: :create

  def index
    if (page == "1")
      @other_posts = Post.includes(:user).with_attached_thumbnail.where(is_pinned: false)
      @pinned_post = Post.includes(:user).with_attached_thumbnail.where(is_pinned: true)

      @posts = Post.includes(:user).with_attached_thumbnail.where(Post.arel_table[:is_pinned].eq(true).or(Post.arel_table[:is_pinned].eq(false)))

      render json: @posts.page(page).per(per_page),
                adapter: :json,
                root: 'data',
                meta: { totalCount: @posts.size }
    elsif
      @posts = Post.includes(:user).with_attached_thumbnail  
      paginated_posts = @posts.page(page).per(per_page)
      render json: paginated_posts,
           adapter: :json,
           root: 'data',
           meta: { totalCount: @posts.size }
    end
  end

  def show
    @post = Post.find(params[:id])
    render json: @post
  end

  def create
    params.delete(:thumbnail) if params[:thumbnail] == 'undefined'
    @post = @current_user.posts.new(post_params)
    if @post.save
      render json: @post
    else
      render json: { errors: @post.errors }, status: 422
    end
  end

  def post_params
    params.permit(
      :title,
      :content,
      :description,
      :thumbnail
    )
  end

  private

  def page
    params[:page] || 1
  end

  def per_page
    params[:per_page] || 10
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User controller class for routing user related actions.
# Note that login is in its own AuthenticationController.
class UsersController < ApplicationController
  before_action :authorize_request, except: :create

  def index
    @users = User.all
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts unless @user.nil?
    render json: @posts
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user
    else
      render json: @user.errors, status: 422
    end
  end

  def toggle_follow
    user = User.find_by(id: params[:id])
    if user
      if @current_user.following?(user)
        unfollow(user)
      else
        follow(user)
      end
    else
      not_found('user')
    end
  end

  def user_params
    params.permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :profile_image,
      :bio
    )
  end

  private

  def follow(user)
    @current_user.follow(user)
    render json: user
  end

  def unfollow(user)
    @current_user.unfollow(user)
    render json: {
      message: 'User unfollowed successfully'
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followings/create.html.erb
<h1>Followings#create</h1>
<p>Find me in app/views/followings/create.html.erb</p>

app/views/followings/destroy.html.erb
<h1>Followings#destroy</h1>
<p>Find me in app/views/followings/destroy.html.erb</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse header">
  <div class="container navigation">
    <%= link_to "Creative Outlet", root_path %>
    <ul>
      <% if logged_in? %>
      <ul>
        <% if current_user.profile_image.attached? %>
          <li> <%= image_tag current_user.profile_image.variant(resize: "20") %> </li>
        <% end %>
        <li> <%= link_to "#{current_user.name}", user_path(current_user.id) %> </li>
        <li> <%= link_to "Logout", logout_path, method: :delete%> </li>
        <% if request.path == '/posts/new' %>
          <li> <button type="submit" form="new-article"> Publish </button> </li>
        <% else %>
          <li id="add-post"> <%= link_to "+", new_post_path%> </li>
        <% end %>
      </ul>
      <% else %>
      <ul>
        <li><%= link_to "Log in", login_path%></li>
        <li><%= link_to "Sign up", new_user_path%> </li>
      </ul>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Creative Outlet </title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <main>
    <%= yield %>
  </main>
  <footer></footer>
</body>
</html>

app/views/posts/_logged_in.html.erb
<div class="content col-md-6">
  <% unless current_user.discover.empty? %>
    <h2 class="category-title"> Discover </h2>
    <% if current_user.nil? %>
      <ul class="posts">
        <%= render @posts %>
      </ul>
    <% else %>
      <ul class="posts">
        <%= render current_user.discover %>
      </ul>
    <% end %>
  <% end %>

  <h2 class="category-title"> Feed </h2>
  <% unless current_user.feed.empty? %>
    <ul class="posts">
      <%= render current_user.feed %>
    </ul>
  <% else %>
    Follow more people you find interesting so they appear in your feed.
  <% end %>
</div>

app/views/posts/_post.html.erb
<li class="post row">
  <div class="col-md-8">
    <%= link_to post.title, post_path(post.id), {class: 'title'} %>
    <% if current_user.nil? %>
      <p> Anonymous </p>
    <% else %>
      <h3 class="author"> 
        <%= link_to post.user.name, user_path(post.user.id) %>
      </h3>
    <% end %>
  </div>
  <div class="col-md-4 text-left">
    <% if post.thumbnail.attached? %>
      <%= image_tag post.thumbnail.variant(resize: "75") %>
    <% end %>
  </div>
</li>

app/views/posts/create.html.erb
Post created successfully

app/views/posts/index.html.erb
<div class="container">
  <% unless current_user.nil? %>
  <%= render 'logged_in' %>
  <% else %>
    <ul class="posts">
      <%= render @posts %>
    </ul>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container new-article-page">
    <%= form_for @post, html: {class: "new-article", id: "new-article"} do |f| %>
    <% if flash[:danger] %>
    <div class="danger"> <%= flash[:danger] %> </div>
    <% end %>
    <%= f.text_field :title, placeholder: 'Article title', class: 'form-control new-article__title new-article__input' %>
    <%= f.text_area :content, placeholder: "What's on your mind?", class: 'form-control new-article__body new-article__input' %>
    <% end %>
</div>

app/views/posts/show.html.erb
<section class="col-md-2 content"> </section>

<section class="col-md-8">
  <h3 class="title"> <%= @post.title %> </h3>
  <p class="content"> <%= @post.content %> </p>
  <% unless current_user.nil? %>
    <p class="byline"> <%= @post.user.name  %> </p>
  <% end %>
</section>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id = "error_explanation" >
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul> 
      <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="new-user">
  <div class="container">
    <h1 class=""> New Profile </h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= render 'shared/error_messages' %>
        <%= form_for @user, html: { class: '' } do |f| %>
        <% if flash[:danger] %>
        <div class="danger"> <%= flash[:danger] %> </div>
        <% end %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.label :profile_image %>
        <%= f.file_field :profile_image, class: 'form-control' %>

        <%= f.label :bio %>
        <%= f.text_area :bio, class: 'form-control new-user__bio', maxlength:'200'%>

        <%= f.submit "Sign up", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user">
  <div class="account-info">
    <div class="profile-image-wrapper">
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image.variant(resize: "100") %>
      <% end %>
    </div>
    <p> <%= @user.name %> </p>
    <p> <%= @user.email %> </p>
    <span> <%= @user.followers.count %> followers </span>
    <p> <%= @user.following.count %> following </p>
    <% unless current_user.nil? %>
      <% unless current_user.following?(@user) %>
        <%= link_to "follow", followings_path(id: @user.id), method: "post" if current_user != @user %>
      <% else %>
        <%= link_to "unfollow", following_path(id: @user.id), method: "delete" %>
      <% end %>
    <% else %>
      <%= link_to "follow", login_path %>
    <% end %>
  </div>
  <div class="user-bio">
    <p>
      <%= @user.bio %>
    </p>
  </div>
</div>
<div class="container">
  <ul class="posts text-center">
    <%= render @posts %>
  </ul>
</div>